services:
  job-alerts:
    image: rubenchek/hiring-compass-au:${HC_IMAGE_TAG:-latest}
    environment:
      HC_ROOT: /app
      HC_SECRETS_DIR: /app/secrets
    volumes:
      - ./secrets:/app/secrets
      - ./run/prod/data:/app/data
      - ./run/prod/logs:/app/logs

  job-enrichment:
    image: rubenchek/hiring-compass-au:${HC_IMAGE_TAG:-latest}
    environment:
      HC_ROOT: /app
      HC_SECRETS_DIR: /app/secrets
    volumes:
      - ./secrets:/app/secrets
      - ./run/prod/data:/app/data
      - ./run/prod/logs:/app/logs

  job-alerts-oauth:
    image: rubenchek/hiring-compass-au:${HC_IMAGE_TAG:-latest}
    environment:
      HC_ROOT: /app
      HC_SECRETS_DIR: /app/secrets
      HC_GMAIL_OAUTH_HOST: 0.0.0.0
      HC_GMAIL_OAUTH_PORT: 8080
      HC_GMAIL_OAUTH_OPEN_BROWSER: "0"
    volumes:
      - ./secrets:/app/secrets
      - ./run/prod/data:/app/data
      - ./run/prod/logs:/app/logs

  notify:
    image: rubenchek/hiring-compass-au:${HC_IMAGE_TAG:-latest}
    environment:
      HC_ROOT: /app
      HC_SECRETS_DIR: /app/secrets
    volumes:
      - ./secrets:/app/secrets
      - ./run/prod/data:/app/data
      - ./run/prod/logs:/app/logs
